#+title: Табы в emacs
#+date: <2023-07-20>
#+keywords: emacs

Узнал что в emacs есть возможность отображать табы, причём
в ванильном емаксе есть даже два режима отображения табов: [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Tab-Bars.html][Tab Bars]] и
[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Tab-Line.html][Window Tab Line]]. И первый и второй отображают вкладки но делают это по разному:

* Tab Bars
Включается командой =tab-bar-mode=, добавляет табы, причем каждый таб является
полноценно настроенным окном emacs, типа =C-x 5 2=, только на этот раз всё
в одном окне. И сочетания у них примерно одинаковые: префикс =C-x t= ведет себя как
=C-x 5= только вместо окошек (фреймов) оперирует вкладками.

+ То что легко запоминается и возможно пригодится:
  + =C-x t 2= - Создать новую вкладку
  + =C-x t 0= - Закрыть текущую вкладку
  + =C-x t 1= - Закрыть все остальные вкладки кроме текущей
  + =C-x t o= / =C-Tab= - Переключиться на следующую вкладку
  + =C-S-Tab= - Переключиться на предыдущую вкладку
  + =C-x t r= - Переименовать вкладку
+ То что, скорее всего, никогда не пригодится:
  + =C-x t b= - Запросить буфер и открыть его в новой вкладке 
  + =C-x t f= - Запросить имя файла и открыть его в новой вкладке
  + =C-x t t= - Префикс, после него нужно вводить ещё одну команду.
    Команда будет выполнена в новой вкладке (сложно, ваще жесть)

В принципе штука интересная, позволяет разделить разные задачи (проекты)
в разные пространства, и, при этом всё остаётся в одном окне приложения.
Но пока не очень понимаю нужна мне эта фича и буду ли я её использовать.
Обычно для этой цели я использую =C-x 5 2=.

* Window Tab Line
Эта штука попроще, включается через =global-tab-line-mode= и добавляет
*ещё одну* панель вкладок, в которой, на этот раз, перечисляются
все открытые когда-либо буферы. =C-x LEFT= и =C-x RIGHT= переключает
между буферами.

Через =M-x customize-variable tab-line-tabs-function= можно
поменять поведение панели вкладок, и, вместо открытых буферов,
например, показать только вкладки буферов с тем же major-mode, или
отображать все буферы, но они будут сгруппированы по своему major-mode.

Но, как бы то ни было, *window tab line* в основном рассчитан на работу с
мышью, и использовать его я, скорее всего, не буду.
